### ISSUE TITLE
enigma2_crash_1471970528 for openxta

### ISSUE THREAD

**Issue by Dima73** [oe-alliance/enigma2-plugins#118]
please see log
http://www.xtrend-alliance.com/index.php?/topic/2105-epgsearch-neue-version-funzt-nicht/#comment-27021

**Comment by RobvanderDoes** [comment]
Yes, it's a known issue with XTA; they'll have to fix that in the image.
That's why I asked http://www.xtrend-alliance.com/index.php?/topic/457-t%C3%A4gliche-tests-mit-dem-xta_v55-image-%E2%80%A6/&page=31#comment-26967 , but no real reaction....

**Comment by arn354** [comment]
xta should use from this repository epgsearchpli and not epgsearch - as long they are closer to openPli
