### ISSUE TITLE
2.3/master branch names

### ISSUE THREAD

**Issue by AbuBaniaz** [oe-alliance/enigma2-plugins#143]
Can we rename the branches please?

master > master-old
2.3 > master

Is anyone still building from the master (old) branch?

**Comment by Schimmelreiter** [comment]
See #50

**Comment by AbuBaniaz** [comment]
OK. I even posted in it.

Is anyone still building from the old one though?

**Comment by Schimmelreiter** [comment]
No idea.
Noone with a clever grep through distro configs? :)

**Comment by AbuBaniaz** [comment]
I have deleted the master branch. It is stale, nobody uses it.
