### ISSUE TITLE
AT: AutoTimers not being saved to disk

### ISSUE THREAD

**Issue by jbleyel** [oe-alliance/enigma2-plugins#172]
See Here -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/591

**Comment by prl001** [comment]
From the previous linked discussion:

> You can take a look to the autotimer plugin and try to find a way to write the xml on each change.
> https://github.com/oe-alliance/enigma2-plugins/blob/2.3/autotimer/src/AutoTimerResource.py

AutoTimerResource.py already has sketched out how to implement saving autotimers.xml on OpenWebif updates:
```
class AutoTimerAddOrEditAutoTimerResource(AutoTimerBaseResource):
	...
	def render(self, req):
		...
		# Save modified xml
		#TODO
		#if config.plugins.autotimer.always_write_config.value:
		#	autotimer.writeXml()
```

Similarly in ```AutoTimerRemoveAutoTimerResource.render()```.

The config variable ```config.plugins.autotimer.always_write_config``` hasn't been added to the code, even as a comment (nor any mechanism for altering it).
