### ISSUE TITLE
IPTV autotimer fix

### ISSUE THREAD

**Issue by devait** [oe-alliance/enigma2-plugins#177]
When viewing an IPTV epg I am unable to set an autotimer. This is mainly due to the serviceref being used by autotimer.py and other classes missing the http://url part of the serviceref from the bouquet.

So, I've made a quick mod and attached the file here. Please tidy up as appropriate (I'm 2 days into python!) and consider integrating into this repo?

Conversations from here: http://www.techkings.org/threads/how-to-record-iptv.123223/page-3

[AutoTimer.zip](https://github.com/oe-alliance/enigma2-plugins/files/1076313/AutoTimer.zip)

**Comment by jbleyel** [comment]
Hi @devait ,
you should make a fork, make your changes and then send a pull request.

I have checked you code and i don't understand some things.
Why do you need the cachedServiceList?
The getFullServiceRef function is not really optimal.
Why do you need extra chkServices for http sref after line 467? 
What will happen if you set overrideAlternatives?

Why do you do that hole thing?
Please compare manual created rec timers for a IPTV channel with your autotimer created rec timers.
They have to be similar for duplicated checks. (sref, description, start, duration, ...)

**Comment by devait** [comment]
Why do you need the cachedServiceList?
For each IPTV autotimer service ref set we need to check all the bouquets for IPTV channels (with http) for a match. Cached to make sure we only create the list of IPTV channels once.

The getFullServiceRef function is not really optimal.
It caches the list as above. I'll see what other optimal changes I can make.

Why do you need extra chkServices for http sref after line 467?
After putting back the http part of the service ref, we run through the checkDuration etc to make sure that the timer is a valid one. Then we call getFullServiceRef. I originally called getFullServiceRef directly after putting back the http part of the service ref but before the checkDuration checks, but this is wasteful if the autotimer checks fail. Calling it after checkDuration etc is optimal.

What will happen if you set overrideAlternatives?
As the whole system is using servicerefs without the http part I presume it will carry on as normal.

As I said I'm only a few days into python and openvix coding so if this won't help others or needs to be tested on multiple platforms etc I'm happy to just keep it to myself as it's primarily written for my situation only.

Thanks for your help.

**Comment by jbleyel** [comment]
One thing again.
Please compare a manual created rec timer for a IPTV channel with one created by your autotimer.
They have to be similar. -> check timers.xml

**Comment by devait** [comment]
Ah yes, it's the same.

**Comment by AbuBaniaz** [comment]
Can someone post a link to the commit where this issue was fixed please? I can't find it.

**Comment by jbleyel** [comment]
You should use the latest version from this repository.

**Comment by AbuBaniaz** [comment]
I did not ask which repository to use. 

Which commit/s fixed the reported problem please?

**Comment by jbleyel** [comment]
I don't find any commit for IPTV.
devait has closed this issue.

**Comment by jbleyel** [comment]
https://github.com/oe-alliance/enigma2-plugins/pull/178

**Comment by AbuBaniaz** [comment]
The issue appears to be still present.
Can someone who knows what to do make/suggest the changes please?

https://github.com/oe-alliance/enigma2-plugins/pull/178/files/44a95bcb2d2e66edea93df8e213e1c5021ca6ace
