### ISSUE TITLE
AutoTimer request via mail

### ISSUE THREAD

**Issue by jbleyel** [oe-alliance/enigma2-plugins#180]
Hello I hope you are well.

I was wondering if you can assist with a couple of issues.

1. Is it possible to add a background zap (fake recording) timer to auto timer. EPG refresh plugin has this feature. If AutoTimer can do this natively, then the need for EPG refresh will be less

2. Some users are reporting issues with AutoTimer. If you filter by service and bouquet the service restriction is ignored. To me, logically a person should not filter by both service and bouquet. However the plugin allows this. 

Is it possible to make the service filter override the bouquet filter/bouquet filter not apply if service filter is enabled?

The thread on ViX forum is titled "Auto timer problem (not obeying filters)" 

Sorry to have e-mailed you. But you are the only that has committed to the plugin recently.

Many thanks in advance.

**Comment by devait** [comment]
I only got involved to fix the issue I was having and I haven't the time or knowledge in this to be honest. Sorry.

**Comment by Dima73** [comment]
1.This is really superfluous, since there is a special plugin for this (EPG refresh).
2.Maybe set "Support \"Fast Scan\"?" as NO

**Comment by Dima73** [comment]
2. Done
https://github.com/OpenPLi/enigma2-plugins/pull/320/commits/ab4817d773dc9367ca04159181ea662255e10c6b#diff-a91a49e9d89dea52d7bbf6037b02d6b4R418

**Comment by AbuBaniaz** [comment]
2.  Done here. Thanks to both @Dima73 and @Huevos 
https://github.com/oe-alliance/enigma2-plugins/commit/ad3481d3c9045fa2a638518328b99501efb613c2

1. With all due respect, EPG refresh is just a "zapper" plugin, I would hardy consider that as being special. You select a service, when it should zap and what type of zap. There are many features in E2 that started as plugins but ended up being incorporated into E2. Permanent timeshift, EPG cache location, Freesat EPG reader, Virgin EPG reader are examples. 

Adding the background zap to autotimer will mean need for the extra plugin is gone.

**Comment by Dima73** [comment]
EPG refresh has three modes:
1)normal zap
2)fake recording
3)PiP/PiP hide

The second and third modes can not be realized through a standard timer, which uses AutoTimer.

**Comment by AbuBaniaz** [comment]
Is "fake recording/background zap" not possible it does not exist yet or because it is not possible to do?

**Comment by Dima73** [comment]
AbuBaniaz
I'm ready to explore new / other improvements for the AutoTimer.
Any suggestions?
A new mode of searching for timers or something else ...

**Comment by AbuBaniaz** [comment]
@Dima73 
Sorry for delay in response.

I would appreciate having an option to have the background zap in autotimer. In reality this is only likely to be used for gathering EPG. The benefit I see in this is that we become more self-contained instead of having to install another plugin. Some functionalities that started out as plugins have been incorporated into the images. An example is permanent/automatic timeshift. I see my request for background zap to be in the same category.
