### ISSUE TITLE
Search on tittle and EPG of scheduled timers

### ISSUE THREAD

**Issue by joniale** [oe-alliance/enigma2-plugins#300]
Dear Developers,
Sometimes an autotimer records the same chapter many times under the same name o very similar names. It would be good to have the option to search and filter the matches in tittle or EPG information for the scheduled timers. In that way, we can easily see/check the recorded chapters that are duplicated. Besides, it makes easy to find specific chapters.
The search should have the option to include subfolders.
Besides, it would be good to have the option to select multiple movie files to be deleted/copied/moved from the Openwebif interface.
Best regards,
Joniale

**Comment by jbleyel** [comment]
The autotimer has an option to prevent duplicates. "Require description to be unique"
For openwebif -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/new/choose

**Comment by joniale** [comment]
This is not addressing the feature but just the example i provided. It would still be a nice feature to be able to search on the EPG of scheduled timers.
