### ISSUE TITLE
Local files of AutoResolution don't work, no translations.

### ISSUE THREAD

**Issue by atom89** [oe-alliance/enigma2-plugins#330]
The local files don't work.
i have tested AutoResolution with openATV and openEight, and different languages. (Dutch and German)
but nothing is being translated.
the local files look ok to me, but they could use an update.

Smokey

**Comment by RobvanderDoes** [comment]
Not sure what is wronh than. I use OpenViX in Dutch, and all translations are there and fine.

**Comment by jbleyel** [comment]
Can we close this?

**Comment by atom89** [comment]
Yes, it's finally fixed after two years ;)
