### ISSUE TITLE
Sat finder stop after zero signal

### ISSUE THREAD

**Issue by pa4th** [oe-alliance/enigma2-plugins#366]
Hello,

Sat finder remains on zero after a complete signal lost. I have to search each evening to get the Astra sats due to mobile living. But with the new Zgemma 9.2S latest openpli, openatv and EGAMI the sat finder works only when there is a signal, but after a lost it won't recover. And remains on zero until I switch to an another satellite and back

I hope that this is the correct form for this problem

Thijs

**Comment by Huevos** [comment]
sat finder is part of enigma2. Please post on the distro you have problems with.

And yes, sat finder will give up on "tune failed fatal". but that should only happen for fixed dishes
