### ISSUE TITLE
AutoResolution Plugin, for translations please insert the line from . import _ in the plugin.py

### ISSUE THREAD

**Issue by shhaldon** [oe-alliance/enigma2-plugins#367]
Hi,

i use the openeight image and your plugin autoresolution is a nice software, but i can't make working translations for it because they didn't work without the following code (line)
**from . import _**
in the **plugin.py**

regards
shhaldon

**Comment by Huevos** [comment]
If there is a missing import please submit a PR. Have you checked the translation code actually exists in __init__.py

**Comment by shhaldon** [comment]
Hi Huevos,
yes i checked the **init.**py and it's ok.
i'am new with git so i don't know how i can create a Pull Request, but i will try it

regards
shhaldon

**Comment by Huevos** [comment]
Create a fork of this repo. Make the change on the fork. Test the change on your local hardware. Push the change back to this repo.

**Comment by shhaldon** [comment]
Hi Huevos,

https://github.com/shhaldon/enigma2-plugins/commit/637d9d1b6405e53db129056313c6e21c06edafb1

thanks, is ok or ?

regards
shhaldon

**Comment by Huevos** [comment]
Ok, that is added now. Try to make your commit texts meaningful. For example...

"[AutoResolution] add missing import"

**Comment by shhaldon** [comment]
Hi Huevos,

 thanks for commit.



>  Try to make your commit texts meaningful. For example...
> 
> "[AutoResolution] add missing import"

ok.

regards
shhaldon
