### ISSUE TITLE
Autotimer - case insensitive search doesn't work for utf-8

### ISSUE THREAD

**Issue by Dima73** [oe-alliance/enigma2-plugins#405]
Eurosport 2 НТВ+ event name --> Снукер."Мастерс".1/4 финала (6+)

Add autotimer:

"Match title" --> снукер
"Search type" --> title starts with or partial match
"Search strictness" --> case-insensitive search

No matches found after searching!

 

Set Match title" --> Снукер
28 matches found after searching!

 

So, case insensitive search doesn't work.

 

The problem is somewhere here:
strncasecmp

https://github.com/OpenPLi/enigma2/blob/103d129496df5b236473dc134d2554ba45456f9c/lib/dvb/epgcache.cpp#L2350

> Yeah, the standard strcmp of C doesn't understand anything but ASCII (7 bits officially). There are "wide char" functions, but afaik they operate on either 16 or 32 bit "expanded" versions of Unicode, not the "compressed" UTF-8 representation. I am not sure how Python and Perl do this, as, like Betacentauri says, case-indepedent comparison is very complex in Unicode and UTF-8 makes it even harder. Bit masking of bit 5 certainly won't work here

**Comment by Dima73** [comment]
My knowledge with c+ is very small.

**Comment by Dima73** [comment]
Maybe need use mbsncasecmp

**Comment by original-birdman** [comment]
That has nothing to do with utf-8.
