### ISSUE TITLE
[AutoTimer] BUG create new timer for old EPG entry

### ISSUE THREAD

**Issue by jbleyel** [oe-alliance/enigma2-plugins#406]
BUG : AutoTimer creates timer for old EPG entries if you have some.

Expected Result : Do not create timer if end time older than now.

**Comment by SoSoSoStupid** [comment]
[The old code](https://github.com/oe-alliance/enigma2-plugins/commit/5e2a11de5b86a76bff9050b3fdb78390c040f76d#r106401595) include this issue, can we replace this now:

> ```
> 			if end < time():
> 			# 	print ("[AutoTimer] Skipping expired timers")
> 				continue
> ```

**Comment by jbleyel** [comment]
Looks feasible.

**Comment by SoSoSoStupid** [comment]
https://github.com/SoSoSoStupid/enigma2-plugins/commit/89dcea608a2bcd8d62b59faea2fe0841789514a5

**Comment by jbleyel** [comment]
Thanks
