### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by AbuBaniaz** [oe-alliance/enigma2-plugins#421]
The `python3` branch of this repo is used by images built  from `nextp3` and `nextp3-ssl111`  oe-alliance branches. `The python3` branch of this repo is intended to exclude plugins that are not python 3 compatible or won't compile in those build environments.

All other branches currently use the `master` branch.  Any commits to the master branch should ideally be also compatible with python 3 and be able to be picked/merged into the python3 branch. 

Hopefully, we can go back to one branch. 

I have deleted the PARTIAL_DESCRIPTION_SEARCH as it is no longer required. Confirmed with @arn354 

The dev branch has also been deleted to avoid confusion. The name itself had implied that is where development is done, when that was not the case when it was created. If it is needed, please respond with the reason.

**Comment by jbleyel** [comment]
Hi @AbuBaniaz, i prefer only master cause my PY3 changes should also work on PY2.
I normally use six and future.
