### ISSUE TITLE
AutoTimerResource `for ... in` inefficiency #1248

### ISSUE THREAD

**Issue by wedebe** [oe-alliance/enigma2-plugins#423]
I believe the `AutoTimerChangeSettingsResource` function could be made more efficient, currently up to 325 iterations would be made if my maths is right (25+24+23...)

```
        for key, value in iteritems(req.args):
            value = value[0]
            if key == 'autopoll':
                config.plugins.autotimer.autopoll.value = True if value == 'true' else False
```

**Comment by jbleyel** [comment]
Do you mean iteritems -> iterkeys and then get value for key?

**Comment by jbleyel** [comment]
I have add debug print after for and i get this output.

10:45:34.1681 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 0
10:45:34.1686 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT maxdaysinfuture
10:45:34.1692 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 1
10:45:34.1696 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT fastscan
10:45:34.1701 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 2
10:45:34.1706 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT notifconflict
10:45:34.1711 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 3
10:45:34.1716 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT add_autotimer_to_tags
10:45:34.1721 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 4
10:45:34.1729 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT disabled_on_conflict
10:45:34.1734 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 5
10:45:34.1739 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT interval
10:45:34.1744 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 6
10:45:34.1748 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT refresh
10:45:34.1753 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 7
10:45:34.1758 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT try_guessing
10:45:34.1763 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 8
10:45:34.1768 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT autopoll
10:45:34.1773 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 9
10:45:34.1777 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT addsimilar_on_conflict
10:45:34.1782 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 10
10:45:34.1787 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT editor
10:45:34.1792 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 11
10:45:34.1797 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT notifsimilar
10:45:34.1802 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 12
10:45:34.1806 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT add_name_to_tags
10:45:34.1811 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT 13
10:45:34.1817 /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes  2021-03-22 10:45:34+0100 [-] AT show_in_extensionsmenu
