### ISSUE TITLE
Question - Merge 2.3 into master.

### ISSUE THREAD

**Issue by jbleyel** [oe-alliance/enigma2-plugins#50]
Some Images use the master branch with some old code and some missing fixes.

What you think about the merge into master step by step?

**Comment by Schimmelreiter** [comment]
I think that's the duty of the image teams that use master.
And if we merged the changes, they could as well switch to 2.3 or 3.0 ...

So I guess if they use an old branch, they do it intentionally.
2.3 also lacks some of the fixes that 3.0 has ... though it makes sense for some boxes to stick with 2.3.

**Comment by jbleyel** [comment]
3.0 ?

**Comment by Schimmelreiter** [comment]
Ah, I see the plugins do not have a separate 3.0 branch ...

Anyways, I think it's up to the teams to use the branch they prefer.
Where would be the point of two identical branches after merging all diffs into master?

**Comment by jbleyel** [comment]
The master should be include the latest commit's and all other branches should only be used for maintenance fixes.
All old / unused branches should be archived and deleted.

IMHO

**Comment by jbleyel** [comment]
What you think about: 

Rename the master to 2.0 maintenance
+
Rename the 2.3 to master
+
Merge all missing commit's from the "2.0 maintenance" to master

!! This is a question to all. !!

**Comment by atvcaptain** [comment]
we have teams do not want the changes from 2.3.
The master is out of support for me.
Use the 2.3 we dont merge back all to master,  the master is the orign branch from this git so that is the problem ?
Then i get info master not needed any more we can start delete the old master

**Comment by jbleyel** [comment]
I'm not a git specialist, rename the master to old and rename the 2.3 to master should be not a problem.
Setting the new master as new origin ???? I don't know.

**Comment by AbuBaniaz** [comment]
Might be an idea to start deleting branches that are no longer used.

**Comment by atvcaptain** [comment]
no we need the history to check infos

**Comment by AbuBaniaz** [comment]
There have been no commits for over a year. other than merges of pull requests which i'm sure were submitted to what the submitter thought was the current branch.

Maybe rename to Master-Not used.
