### ISSUE TITLE
IMDB no longer working

### ISSUE THREAD

**Issue by kiddac** [oe-alliance/enigma2-plugins#510]
It seems IMDB changed something on their site last night. 
This means this plugin no longer brings back any data. Every request will no display "No details found"
Plugin needs investigating to see if this is an IMDB temporary error, or that IMDB have changed their HTML which means the IMDB plugin needs rewriting to pick up these changes

**Comment by adoxa** [comment]
I'm working on it.

**Comment by kiddac** [comment]
I was also looking into this yesterday. 
There is now limited data on the first page in the actual html.
There is application json as the bottom of the dom content that does have all the data for all fields.
For simplicity, rather than loading and reading the json (which would require a bit of rewrite, you could use the regex matching on this json section to get all the info. @adoxa

**Comment by adoxa** [comment]
Finally did the rewrite. :)
