### ISSUE TITLE
iMDB work now

### ISSUE THREAD

**Issue by Belfagor2005** [oe-alliance/enigma2-plugins#541]
https://github.com/oe-alliance/enigma2-plugins/blob/31483a76be8a5829e132ebc02506fd0eaf963af9/imdb/src/plugin.py#L348

i have tested and ssl fixed..   
![1_0_19_BCC_3A2_110_EEEE0000_0_0_0_20220826191856](https://user-images.githubusercontent.com/72314956/186958548-6eac30b7-576f-4267-8e45-2df61f1d795e.jpg)
[plugin.zip](https://github.com/oe-alliance/enigma2-plugins/files/9435177/plugin.zip)

**Comment by Huevos** [comment]
This plugin is working for us. 

What problem are you trying to fix? What image distro are you using?

**Comment by Huevos** [comment]
Please be aware OpenATV, OpenBH and OpenViX use the new downloader in enigma2 and do not have any problems with this plugin.

https://github.com/OpenViX/enigma2/blob/Developer/lib/python/Tools/Downloader.py

**Comment by Belfagor2005** [comment]
No show any

and now work

**Comment by Huevos** [comment]
Please answer, 
1) which image are you using
2) which version
3) which build

**Comment by Belfagor2005** [comment]
atv  6.4 for now

![1_0_19_BBE_3A2_110_EEEE0000_0_0_0_20220826212447](https://user-images.githubusercontent.com/72314956/186977279-ee0e9e44-16b6-4666-8d78-016f420b3ff7.jpg)

**Comment by Huevos** [comment]
So, for me it works fine with the new downloader.

![1](https://user-images.githubusercontent.com/2067864/186977663-e6cd085e-0b0d-4652-a111-d7b2edfedcc6.jpg)

Or is there something I am not understanding?

**Comment by Belfagor2005** [comment]
sorry my english translated
I didn't know about the downloader.py
Anyway, if it didn't work on atv 6.4, I applied my changes and it worked.
Welcome the new downloader,
I just made a report.
Regards

**Comment by Belfagor2005** [comment]
this is crash 

01:04:11.3473   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 238, in action
01:04:11.3478   File "/usr/lib/enigma2/python/Plugins/Extensions/IMDb/plugin.py", line 348, in showDetails
01:04:11.3481   File "/usr/lib/enigma2/python/Tools/Downloader.py", line 27, in start
01:04:11.3484   File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
01:04:11.3487   File "/usr/lib/python3.9/urllib/request.py", line 517, in open
01:04:11.3490   File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
01:04:11.3492   File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
01:04:11.3494   File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
01:04:11.3503   File "/usr/lib/python3.9/urllib/request.py", line 1350, in do_open
01:04:11.3507   File "/usr/lib/python3.9/http/client.py", line 1371, in getresponse
01:04:11.3510   File "/usr/lib/python3.9/http/client.py", line 319, in begin
01:04:11.3513   File "/usr/lib/python3.9/http/client.py", line 280, in _read_status
01:04:11.3516   File "/usr/lib/python3.9/socket.py", line 704, in readinto
01:04:11.3518   File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
01:04:11.3522   File "/usr/lib/python3.9/ssl.py", line 1099, in read
01:04:11.3526 socket.timeout: The read operation timed out
01:04:11.3526 [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.HelpableActionMap object at 0xad3e1ca0>>,('OkCancelActions', 'ok')) failed)

**Comment by Huevos** [comment]
The new downloader is in OpenATV branch 7.0... not in branch 6.4.

**Comment by Belfagor2005** [comment]
this crash is image atv 7.0
and i applicate on 6.4 

openATV Enigma2 crash log

crashdate=ven ago 26 01:04:11 2022
compiledate=Aug 21 2022
skin=oZeta-FHD/skin.xml
sourcedate=2022-08-21
branch=7.0
rev=31604+2b7d289
component=Enigma2

stbmodel=H9Combo
stbmodel=h9combo
kernelcmdline=root=/dev/mmcblk0p23 rootsubdir=linuxrootfs2 rootfstype=ext4 kernel=/dev/mmcblk0p20 console=ttyAMA0,115200 blkdevparts=mmcblk0:1M(fastboot),1M(bootargs),18M(recovery),2M(bootoptions),2M(deviceinfo),4M(baseparam),4M(pqparam),4M(logo),40M(fastplay),20M(kernel),20M(trustedcore),4M(misc),1024M(system),150M(vendor),306M(e2tv),256M(cache),50M(private),8M(securestore),16M(linuxkernel1),16M(linuxkernel2),16M(linuxkernel3),16M(linuxkernel4),-(userdata) hbcomp=/dev/block/mmcblk0p13 mem=937M mmz=ddr,0,0,60M vmalloc=500M
nimsockets=NIM Socket 0:
imageversion=box_type=zgemmah9combo
imageissue=Welcome to openATV for %h


01:02:52.0052 [Enigma] Python path is '/usr/lib/enigma2/python'.
01:02:52.0054 [Enigma] DVB API version 5, DVB API version minor 11.
01:02:52.0054 [Enigma] Enigma debug level 3.
01:03:26.1082   File "/usr/lib/enigma2/python/StartEnigma.py", line 945, in <module>
    runScreenTest()  # Start running the first screen.
01:03:26.1083   File "/usr/lib/enigma2/python/StartEnigma.py", line 371, in runScreenTest
    plugins.readPluginList(resolveFilename(SCOPE_PLUGINS))
01:03:26.1084   File "/usr/lib/enigma2/python/Components/PluginComponent.py", line 57, in readPluginList
01:03:26.1084   File "/usr/lib/enigma2/python/Tools/Import.py", line 2, in my_import
01:03:26.1084   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
01:03:26.1085   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
01:03:26.1085   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
01:03:26.1086   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
01:03:26.1086   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
01:03:26.1086   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
01:03:26.1087   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
01:03:26.1087   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
01:03:26.1088   File "/usr/lib/enigma2/python/Plugins/Extensions/oZsetup/__init__.py", line 29, in <module>
    language.addCallback(localeInit())
01:03:26.1088   File "/usr/lib/enigma2/python/Components/Language.py", line 34, in addCallback
01:03:26.1169   File "/usr/lib/enigma2/python/StartEnigma.py", line 945, in <module>
    runScreenTest()  # Start running the first screen.
01:03:26.1170   File "/usr/lib/enigma2/python/StartEnigma.py", line 371, in runScreenTest
    plugins.readPluginList(resolveFilename(SCOPE_PLUGINS))
01:03:26.1171   File "/usr/lib/enigma2/python/Components/PluginComponent.py", line 57, in readPluginList
01:03:26.1171   File "/usr/lib/enigma2/python/Tools/Import.py", line 2, in my_import
01:03:26.1172   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
01:03:26.1172   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
01:03:26.1172   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
01:03:26.1173   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
01:03:26.1173   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
01:03:26.1173   File "/usr/lib/enigma2/python/Plugins/Extensions/oZsetup/plugin.py", line 9, in <module>
    from .__init__ import _
01:03:26.1174   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
01:03:26.1174   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
01:03:26.1175   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
01:03:26.1175   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
01:03:26.1176   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
01:03:26.1176   File "/usr/lib/enigma2/python/Plugins/Extensions/oZsetup/__init__.py", line 29, in <module>
    language.addCallback(localeInit())
01:03:26.1176   File "/usr/lib/enigma2/python/Components/Language.py", line 34, in addCallback
01:03:28.6309 [eServicePeer] ADD Peer atemionemesis=atemionemesis.local:8001
01:03:28.6390 [eServicePeer] ADD Peer atemionemesis=atemionemesis.local:8001
01:03:29.4540 [eDVBPESReader] Created. Opening demux
01:03:29.4541 [eDVBPESReader] Created. Opening demux
01:04:11.3472 Traceback (most recent call last):
01:04:11.3473   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 238, in action
01:04:11.3478   File "/usr/lib/enigma2/python/Plugins/Extensions/IMDb/plugin.py", line 348, in showDetails
01:04:11.3481   File "/usr/lib/enigma2/python/Tools/Downloader.py", line 27, in start
01:04:11.3484   File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
01:04:11.3487   File "/usr/lib/python3.9/urllib/request.py", line 517, in open
01:04:11.3490   File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
01:04:11.3492   File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
01:04:11.3494   File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
01:04:11.3503   File "/usr/lib/python3.9/urllib/request.py", line 1350, in do_open
01:04:11.3507   File "/usr/lib/python3.9/http/client.py", line 1371, in getresponse
01:04:11.3510   File "/usr/lib/python3.9/http/client.py", line 319, in begin
01:04:11.3513   File "/usr/lib/python3.9/http/client.py", line 280, in _read_status
01:04:11.3516   File "/usr/lib/python3.9/socket.py", line 704, in readinto
01:04:11.3518   File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
01:04:11.3522   File "/usr/lib/python3.9/ssl.py", line 1099, in read
01:04:11.3526 socket.timeout: The read operation timed out
01:04:11.3526 [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.HelpableActionMap object at 0xad3e1ca0>>,('OkCancelActions', 'ok')) failed)

**Comment by jbleyel** [comment]
The downloader needs to be removed from IMDb plugin.
There is no progress needed.
