### ISSUE TITLE
[IMDb] Search results

### ISSUE THREAD

**Issue by adoxa** [oe-alliance/enigma2-plugins#549]
IMDb has changed the search results, causing the regex to fail. However, it now includes JSON in the page, and I've got that working. Any thoughts on how episodes should be displayed, if at all?

**Comment by scriptmelvin** [comment]
Good work @adoxa, thanks! I would display episodes like it was (although I can't recall how that was, and I have no screenshots). I never cared for episodes myself.

Anyone else want to comment?

**Comment by adoxa** [comment]
I don't really recall, either, hence the question. :) I might add an option to skip them. My current thinking is to use the series title with the episode title(s) below it:

Short:
Title (year)
Title (year(s))
- Episode (year; Sn En)

Long:
Title (year; type; top cast)
Title (years; type)
- Episode (year; Sn En; top cast)

(Top cast is two actors.)

**Comment by Huevos** [comment]
Looks good. Does this require skin changes?

**Comment by adoxa** [comment]
No, it's still only menu text and the option should be picked up from `setup.xml`.
