### ISSUE TITLE
[dreamexplorer] crashes after "Sort by date"

### ISSUE THREAD

**Issue by retoch44** [oe-alliance/enigma2-plugins#630]
Here is my log:

12:23:57.8718 [eDVBPESReader] Created. Opening demux
12:23:57.8719 [eDVBPESReader] Created. Opening demux
12:23:58.6519 [gPixmap] unimplemented: scale on non-accel surface 32->16 bpp
12:24:02.6759 [gPixmap] unimplemented: scale on non-accel surface 32->16 bpp
12:24:33.1464 Traceback (most recent call last):
12:24:33.1465   File "/usr/lib/enigma2/python/StartEnigma.py", line 84, in processDelay
12:24:33.1559     callback(*retVal)
12:24:33.1562   File "/usr/lib/enigma2/python/Plugins/Extensions/DreamExplorer/plugin.py", line 446, in SysExecution
12:24:33.1607   File "/usr/lib/enigma2/python/Plugins/Extensions/DreamExplorer/plugin.py", line 670, in sortDate
12:24:33.1610   File "/usr/lib/enigma2/python/Plugins/Extensions/DreamExplorer/myFileList.py", line 353, in sortDate
12:24:33.1614 TypeError: sort() takes no positional arguments
12:24:33.1615 [ePyObject] (PyObject_CallObject(<bound method Session.processDelay of <__main__.Session object at 0xac339190>>,()) failed)

openATV Enigma2 crash log

crashdate=Do Nov  9 12:24:33 2023
compiledate=Nov  7 2023
skin=MetrixHD/skin.MySkin.xml
sourcedate=2023-11-07
branch=7.3
rev=32864+7f613dc
component=Enigma2

model=gb7252
machinebuild=gbue4k
imageversion=7.3
imagebuild=20231108

Gigablue UE 4K with OpenATV 7.3, but crashes with all versions of 7.x if I remember right.

**Comment by jbleyel** [comment]
Please use FileCommander instead and tell us what is missing in FileCommander because we will remove the DreamExplorer from the feed.

**Comment by retoch44** [comment]
Thanks, I added an issue at this FileCommander [repo](https://github.com/E2OpenPlugins/e2openplugin-FileCommander/issues/23) some time ago, but am no sure if this is the right one.

**Comment by jbleyel** [comment]
No .. the FileCommander in openATV is a core component of enigma.

Please create the issue here -> https://github.com/openatv/enigma2
