### ISSUE TITLE
Add sub button as a new function

### ISSUE THREAD

**Issue by popking159** [oe-alliance/enigma2-plugins#687]
Thanks for updating this great plugin , 
I ask if it is possible to add a new option in the plugin , when searching for a movie and choose the desired one , all data about this movie appears , can sub button be added here ? to call subssupport plugin and make search for the movie name .

**Comment by adoxa** [comment]
There's a lot of plugins here, you should be more specific. Do you mean IMDb? I'm not sure that's warranted, since wouldn't it need the name of the recording? Assuming you're using IMDb to determine if you want to record.

**Comment by popking159** [comment]
Yes I mean IMDb plugin , I need to use the English title of the movie to call subssupport plugin and search for subtitles.

**Comment by adoxa** [comment]
Here's an updated [plugin.py(.gz)](https://github.com/user-attachments/files/17268545/plugin.py.gz) to see if it what's you want (I'm assuming you know how to install that). It adds "SubsSupport search" to the context menu (between YTTrailer and the videos). Untested, here's hoping I did it right...
